### ISSUE TITLE
Platform support?

### ISSUE THREAD

**Issue by reiddraper** [timescaledb/timescaledb#1]
What are the supported platforms for timescaledb? I've tried compiling on MacOS and FreeBSD, without success.

**Comment by RobAtticus** [comment]
Sorry to hear that! What versions of those two platforms have you tried? I don't know about FreeBSD but most of us develop on MacOS should it should work there. We do also need to clarify which PostgreSQL versions to use. We've only tested on 9.6.1 and 9.6.2.

Also any error messages you had while compiling would be helpful.

**Comment by RobAtticus** [comment]
Looks like it was a Postgres version issue (worked with you offline). Updated the docs to make note that 9.6 is needed.
