### ISSUE TITLE
Error when using sample data

### ISSUE THREAD

**Issue by solugebefola** [timescaledb/timescaledb#7]
OS: MacOS Sierra
Install method: homebrew

I was trying to use the sample data.  I followed the setup instructions on http://docs-new.timescaledb.com/other-sample-datasets for the `device_small` dataset and had a problem with the command
```
psql -U postgres -d devices_small -h localhost < devices_small.bak
```
because I did not have a `postgres` superuser.

I created a `postgres` user, did a `DROP DATABASE devices_small` and tried again.  Most of it went fine, but there was one error.
```
ERROR:  function _timescaledb_internal.on_modify_main_table() does not exist
```
and there doesn't appear to be any data in the ~database~ `readings` table, but there is data in the `device_info` table.

Update: I tried with the `weather_small` dataset and got the same error and again, no data in the `conditions` table, but the `locations` table has data

**Comment by RobAtticus** [comment]
I've uploaded new datasets built on the latest release (0.0.4-beta) and both of these issues should be fixed:

1. You can use any user to restore the DB
2. The above ERROR no longer happens

**Comment by solugebefola** [comment]
Seems to work now!

**Comment by chylvina** [comment]
OS: MacOS Sierra
Install method: docker, tag: latest (should be 0.0.7-beta)

I tried with the weather_small, weather_big, devices_small and got no errors. But there is no data in `conditions` table, has some data in `locations` table.
